[2025-03-06T16:37:24.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-06T16:37:24.063+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_flow.load_exchangeRate_python_job manual__2025-03-06T16:37:18.680122+00:00 [queued]>
[2025-03-06T16:37:24.078+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_flow.load_exchangeRate_python_job manual__2025-03-06T16:37:18.680122+00:00 [queued]>
[2025-03-06T16:37:24.079+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-06T16:37:24.095+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): load_exchangeRate_python_job> on 2025-03-06 16:37:18.680122+00:00
[2025-03-06T16:37:24.102+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2058) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-06T16:37:24.104+0000] {standard_task_runner.py:72} INFO - Started process 2061 to run task
[2025-03-06T16:37:24.102+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_flow', 'load_exchangeRate_python_job', 'manual__2025-03-06T16:37:18.680122+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag_***_spark.py', '--cfg-path', '/tmp/tmpr93nd_ze']
[2025-03-06T16:37:24.105+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask load_exchangeRate_python_job
[2025-03-06T16:37:24.170+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_flow.load_exchangeRate_python_job manual__2025-03-06T16:37:18.680122+00:00 [running]> on host bfcfbd2155da
[2025-03-06T16:37:24.273+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haonv' AIRFLOW_CTX_DAG_ID='spark_flow' AIRFLOW_CTX_TASK_ID='load_exchangeRate_python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T16:37:18.680122+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-06T16:37:18.680122+00:00'
[2025-03-06T16:37:24.274+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-06T16:37:24.306+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2025-03-06T16:37:24.308+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://172.18.0.3:7077 --name arrow-spark --deploy-mode client jobs/python/load_exchangeRateToDW.py
[2025-03-06T16:37:28.172+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SparkContext: Running Spark version 3.5.5
[2025-03-06T16:37:28.178+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-06T16:37:28.179+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SparkContext: Java version 17.0.14
[2025-03-06T16:37:28.308+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-06T16:37:28.507+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO ResourceUtils: ==============================================================
[2025-03-06T16:37:28.509+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-06T16:37:28.509+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO ResourceUtils: ==============================================================
[2025-03-06T16:37:28.510+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SparkContext: Submitted application: ExchangeRateToDW
[2025-03-06T16:37:28.547+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-06T16:37:28.567+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO ResourceProfile: Limiting resource is cpu
[2025-03-06T16:37:28.570+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-06T16:37:28.670+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SecurityManager: Changing view acls to: ***
[2025-03-06T16:37:28.671+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SecurityManager: Changing modify acls to: ***
[2025-03-06T16:37:28.672+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SecurityManager: Changing view acls groups to:
[2025-03-06T16:37:28.674+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SecurityManager: Changing modify acls groups to:
[2025-03-06T16:37:28.675+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:28 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-06T16:37:29.245+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO Utils: Successfully started service 'sparkDriver' on port 40379.
[2025-03-06T16:37:29.359+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO SparkEnv: Registering MapOutputTracker
[2025-03-06T16:37:29.439+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-06T16:37:29.462+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-06T16:37:29.463+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-06T16:37:29.469+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-06T16:37:29.503+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-45b7bbd0-10ea-475a-9d2c-ded19ca34e1d
[2025-03-06T16:37:29.521+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-06T16:37:29.546+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-06T16:37:29.839+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-06T16:37:29.933+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-03-06T16:37:29.948+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:29 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-03-06T16:37:30.153+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.18.0.3:7077...
[2025-03-06T16:37:30.239+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO TransportClientFactory: Successfully created connection to /172.18.0.3:7077 after 49 ms (0 ms spent in bootstraps)
[2025-03-06T16:37:30.375+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250306163730-0010
[2025-03-06T16:37:30.386+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33091.
[2025-03-06T16:37:30.387+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO NettyBlockTransferService: Server created on bfcfbd2155da:33091
[2025-03-06T16:37:30.389+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-06T16:37:30.398+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, bfcfbd2155da, 33091, None)
[2025-03-06T16:37:30.406+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO BlockManagerMasterEndpoint: Registering block manager bfcfbd2155da:33091 with 434.4 MiB RAM, BlockManagerId(driver, bfcfbd2155da, 33091, None)
[2025-03-06T16:37:30.409+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, bfcfbd2155da, 33091, None)
[2025-03-06T16:37:30.411+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, bfcfbd2155da, 33091, None)
[2025-03-06T16:37:30.810+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:30 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-06T16:37:31.437+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-06T16:37:31.451+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-06T16:37:31.495+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250306163730-0010/0 on worker-20250306162317-172.18.0.10-36791 (172.18.0.10:36791) with 2 core(s)
[2025-03-06T16:37:31.497+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO StandaloneSchedulerBackend: Granted executor ID app-20250306163730-0010/0 on hostPort 172.18.0.10:36791 with 2 core(s), 1024.0 MiB RAM
[2025-03-06T16:37:31.499+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250306163730-0010/1 on worker-20250306162317-172.18.0.8-46753 (172.18.0.8:46753) with 2 core(s)
[2025-03-06T16:37:31.500+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO StandaloneSchedulerBackend: Granted executor ID app-20250306163730-0010/1 on hostPort 172.18.0.8:46753 with 2 core(s), 1024.0 MiB RAM
[2025-03-06T16:37:31.574+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250306163730-0010/0 is now RUNNING
[2025-03-06T16:37:31.578+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:31 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250306163730-0010/1 is now RUNNING
[2025-03-06T16:37:33.348+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-03-06T16:37:33.349+0000] {spark_submit.py:641} INFO - File "/opt/***/jobs/python/load_exchangeRateToDW.py", line 65, in <module>
[2025-03-06T16:37:33.352+0000] {spark_submit.py:641} INFO - .load()
[2025-03-06T16:37:33.353+0000] {spark_submit.py:641} INFO - ^^^^^^
[2025-03-06T16:37:33.354+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/streaming/readwriter.py", line 304, in load
[2025-03-06T16:37:33.355+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-06T16:37:33.357+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-06T16:37:33.378+0000] {spark_submit.py:641} INFO - pyspark.errors.exceptions.captured.AnalysisException: Failed to find data source: kafka. Please deploy the application as per the deployment section of Structured Streaming + Kafka Integration Guide.
[2025-03-06T16:37:33.488+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-06T16:37:33.489+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-06T16:37:33.509+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO SparkUI: Stopped Spark web UI at http://bfcfbd2155da:4041
[2025-03-06T16:37:33.515+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-06T16:37:33.522+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-06T16:37:33.548+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-06T16:37:33.564+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO MemoryStore: MemoryStore cleared
[2025-03-06T16:37:33.566+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO BlockManager: BlockManager stopped
[2025-03-06T16:37:33.575+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-06T16:37:33.578+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-06T16:37:33.590+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO SparkContext: Successfully stopped SparkContext
[2025-03-06T16:37:33.590+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO ShutdownHookManager: Shutdown hook called
[2025-03-06T16:37:33.591+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-6bf2f532-5f75-4102-b0cd-c928aff95a42
[2025-03-06T16:37:33.594+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-71d6be90-73cd-40f0-949f-2aac965039df
[2025-03-06T16:37:33.598+0000] {spark_submit.py:641} INFO - 25/03/06 16:37:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-71d6be90-73cd-40f0-949f-2aac965039df/pyspark-1ac16e37-52cb-442e-8ec9-a0e84eeb9901
[2025-03-06T16:37:33.639+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.18.0.3:7077 --name arrow-spark --deploy-mode client jobs/python/load_exchangeRateToDW.py. Error code is: 1.
[2025-03-06T16:37:33.644+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=spark_flow, task_id=load_exchangeRate_python_job, run_id=manual__2025-03-06T16:37:18.680122+00:00, execution_date=20250306T163718, start_date=20250306T163724, end_date=20250306T163733
[2025-03-06T16:37:33.712+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-06T16:37:33.712+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task load_exchangeRate_python_job (Cannot execute: spark-submit --master spark://172.18.0.3:7077 --name arrow-spark --deploy-mode client jobs/python/load_exchangeRateToDW.py. Error code is: 1.; 2061)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.18.0.3:7077 --name arrow-spark --deploy-mode client jobs/python/load_exchangeRateToDW.py. Error code is: 1.
[2025-03-06T16:37:33.755+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-06T16:37:33.781+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-06T16:37:33.787+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
